### ISSUE TITLE
Make one for the trains, too?

### ISSUE THREAD

**Issue by jds11111** [custom-components/sensor.ctabustracker#1]
**Is your feature request related to a problem? Please describe.**
I like how you have set this up to make a single call to the API, but then extract multiple busses from it. 
It would be nice to do the same with trains. I can extract just the time of arrival from one ping of the API, but need to make multiple pings to get the same thing for two trains.  There is a way to do it from templates, but it is pretty involved, and I am having trouble making it work.  I suspect that it is not a big modification to your python code.

**Describe the solution you'd like**

Well, like you have already, but for trains.  Also, it would be great to extract out the lon and lat of each train, to put it on a map. 
The JSON is a little bit different from the trains, and the http, of course.  The call to the API looks like this:
`https://lapi.transitchicago.com/api/1.0/ttarrivals.aspx?key=xxxxxxxxxxxxxxx&stpid=yyyyy&outputType=JSON`
where `xxxxxxxxxxxxxxxx` is the key you apply for [here](https://www.transitchicago.com/developers/traintrackerapply/), and
`yyyyy` is the station map id (including direction) that you find [here](https://www.transitchicago.com/developers/ttdocs/#_Toc296199908) (scroll down to the table called **Individual Stop IDs Quick Reference**, and get the number on the left side for your desired station and direction.

This pulls out the data, all of which is in an array value_json.ctatt.eta, where then [0] is the first train, etc.  Inside that is 'arrT', which is the arrival time, 'lon' and 'lat'. It is all well documented by CTA.

**Describe alternatives you've considered**
I am trying to do this with yaml and the REST platform, but is rather complex when getting all the bits from the array.

**Additional context**
(Wish I knew python better).

**Comment by ludeeus** [comment]
That should not be added here.
Someone can fork this repo and make `sensor.ctatraintracker` or  even better `ctatracker` that handles both, since I cant use that service, I will not be doing it.

**Comment by jds11111** [comment]
Fair enough.  Thanks for considering it.
